"""product price added

Revision ID: c6a172b4d8f7
Revises:
Create Date: 2025-08-12 17:01:42.660796

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c6a172b4d8f7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("price", sa.Float(), nullable=False))
    op.alter_column("product", "catalog_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("product", "catalog_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("product", "price")
    # ### end Alembic commands ###
